---
title: "RNA-Protein"
author: Marc Vaudel
date: 2019-10-28
output: 
    github_document:
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# RNA-Protein

In the [_novel peptides_](novel_peptides.md) and [_variatoin analysis_](variation_analysis.md) chapters, novel and variant peptides were identified by Johansson _et al._ [(1)](#references) using a proteogenomic search strategy, where genomic data are used to inform the proteomics search strategy. It is possible to use RNA sequencing data complementarily or instead of the genetic sequence to identify non-canonical protein products.

##### [:thought_balloon:](answers.md#thought_balloon-what-are-the-advantages-and-shortcomings-of-using-transcript-sequences-instead-of-or-in-addition-to-genomic-data) _What are the advantages and shortcomings of using transcript sequences instead of or in addition to genomic data?_


## References

(1) [title](https://www.ncbi.nlm.nih.gov/pubmed/pmid)


